#!/bin/sh

msg() {
    echo "\033[1;32m-->\033[0m $*"
}

compiler=${1:-rathaxes}

if ! type $compiler >/dev/null ; then
    msg "Cannot find the rathaxes compiler, install it or provide it like:"
    msg "$0 /path/to/rathaxes"
    exit 1
fi

msg "clearing cache"
$compiler cache clear

set -e

for f in types.rti main.rti log.rti ; do
    msg "registering rti $f"
    $compiler rti-register $f
done

for f in types.blt log.blt main.blt ; do
    msg "registring blt $f"
    $compiler blt-register $f
done

msg "generating for Linux"
$compiler generate linux hello.rtx
