#!/bin/sh

name=buildbot-slave

msg() {
    echo "--> $0:" $*
}

cd_approot() {
    cd slave
}

create_virtualenv() {
    local env_directory="$HOME/env"

    msg "creating virtualenv"
    if [ ! -d $env_directory ] ; then
        virtualenv $env_directory
        $env_directory/bin/pip install -E $env_directory pip --upgrade
    fi

    . $env_directory/bin/activate
}

install_dependencies() {
    local download_cache="$HOME/.pip/downloads/"

    msg "installing dependencies"
    if [ -f requirements.txt ] ; then
        [ -d $download_cache ] || mkdir -p $download_cache
        pip install --quiet --download-cache=$download_cache -r requirements.txt
    fi

    # We can't install the latest version of buildbot with pip because the
    # setup.py is not in the root directory.
    # -e git+git://github.com/buildbot/buildbot.git#egg=buildbot
    local buildbot_repo="$HOME/data/buildbot"
    if [ ! -d $buildbot_repo ] ; then
        msg "installing buildbot"
        mkdir -p $buildbot_repo
        git clone git://github.com/buildbot/buildbot.git $buildbot_repo
        ( cd "$buildbot_repo/slave" ; exec python setup.py install )
    fi
}

install_application() {
    msg "installing application to ~/"
    rsync -aH --delete --exclude "data" * $HOME/
}

cd_approot
create_virtualenv
install_dependencies
install_application
